trigger:
        branches:
          include:
          - master
      
pool:
  name: Azure Pipelines
  vmImage: 'windows-2019'
  demands:
    - npm
    - msbuild
    - visualstudio

variables: 
  configuration: release
  BuildConfiguration: "Release"
  platform: x64

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: NuGetToolInstaller@0
      displayName: 'Use NuGet 4.4.1'
      inputs:
        versionSpec: 4.4.1
    - task: NuGetCommand@2
      displayName: 'NuGet restore'
      inputs:
        restoreSolution: '$(Parameters.solution)'
        vstsFeed: '34356gsgv643a'
    - task: Npm@1
      displayName: 'npm install'
      inputs:
        workingDir: angularfoldername
        verbose: false
    - task: Npm@1
      displayName: 'npm custom'
      inputs:
        command: custom
        workingDir: angularfoldername
        verbose: false
        customCommand: 'run build'
    - task: MSBuild@1
      displayName: 'Build solution dotnet.csproj'
      inputs:
        solution: dotnet.csproj
        msbuildArguments: '/t:build /p:outputpath="$(build.artifactstagingdirectory)" /property:langversion=latest'
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: '$(Parameters.TestProjects)'
        arguments: '--configuration $(BuildConfiguration)'
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)\_PublishedWebsites\dotnet\angularfolder'
      inputs:
        SourceFolder: 'angularfoldername'
        Contents: '**'
        TargetFolder: '$(build.artifactstagingdirectory)\_PublishedWebsites\dotnet\angularfoldername'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)\_PublishedWebsites'