pool:
  vmImage: 'ubuntu-latest'

trigger:
- master

variables:
  buildConfiguration: 'release'

steps:
- task: DotNetCoreCLI@2
  displayName: dotnet build $(buildConfiguration)
  inputs:
    command: build
    arguments: '--configuration $(buildConfiguration)' # Update this to match your need

- task: Npm@1
  displayName: "npm install"
  inputs:
    command: 'install'
    workingDir: 'ClientApp'

- task: Npm@1
  displayName: "npm run build:$(buildConfiguration)"
  inputs:
    command: 'custom'
    workingDir: 'ClientApp'
    customCommand: 'run build:$(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: "dotnet publish $(buildConfiguration)"
  inputs:
    command: 'publish'
    publishWebProjects: True
    arguments: '-c $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True